// Code generated by Slice Machine. Customize after running `npm run slicemachine`.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<string, prismic.AnyRegularField | prismic.GroupField>,
  TLang extends string,
> =
  | prismic.ContentRelationshipField<
      TRelationship["id"],
      TLang,
      Simplify<
        PickContentRelationshipFieldData<
          TRelationship["customtypes"][number],
          TData,
          TLang
        >
      >
    >
  | prismic.ContentRelationshipField<TRelationship["id"]>;

type HeroSliceDefaultPrimary = {
  name: prismic.KeyTextField;
  title: prismic.KeyTextField;
  subtitle: prismic.KeyTextField;
  cta_text: prismic.KeyTextField;
  cta_link: prismic.LinkField;
};

type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

type HeroSlice = prismic.SharedSlice<"hero", HeroSliceDefault>;

type HomepageDocumentDataSlicesSlice = HeroSlice;

interface HomepageDocumentData {
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>;
  meta_title: prismic.KeyTextField;
  meta_description: prismic.KeyTextField;
}

export type HomepageDocument = prismic.PrismicDocumentWithUID<
  Simplify<HomepageDocumentData>,
  "homepage"
>;

declare module "@prismicio/client" {
  namespace Content {
    export type {
      HeroSlice,
      HeroSliceDefault,
      HeroSliceDefaultPrimary,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
    };
  }

  type AllDocumentTypes = HomepageDocument;
}
